# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registro_revistas.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_titulo_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_titulo_revista.setGeometry(QtCore.QRect(210, 80, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_titulo_revista.setFont(font)
        self.entrada_titulo_revista.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(170, 255, 0);")
        self.entrada_titulo_revista.setText("")
        self.entrada_titulo_revista.setObjectName("entrada_titulo_revista")
        self.entrada_precio_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio_revista.setGeometry(QtCore.QRect(210, 130, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_precio_revista.setFont(font)
        self.entrada_precio_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_precio_revista.setText("")
        self.entrada_precio_revista.setObjectName("entrada_precio_revista")
        self.entrada_ditribuidor_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_ditribuidor_revista.setGeometry(QtCore.QRect(210, 180, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_ditribuidor_revista.setFont(font)
        self.entrada_ditribuidor_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_ditribuidor_revista.setText("")
        self.entrada_ditribuidor_revista.setObjectName("entrada_ditribuidor_revista")
        self.entrada_registrar_revista = QtWidgets.QPushButton(self.centralwidget)
        self.entrada_registrar_revista.setGeometry(QtCore.QRect(230, 550, 321, 81))
        self.entrada_registrar_revista.setStyleSheet("alternate-background-color: rgb(61, 165, 255);\n"
"background-color: rgb(56, 142, 255);\n"
"border-color: rgb(32, 47, 255);")
        self.entrada_registrar_revista.setObjectName("entrada_registrar_revista")
        self.entrada_date_devolucion = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_date_devolucion.setGeometry(QtCore.QRect(210, 330, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_date_devolucion.setFont(font)
        self.entrada_date_devolucion.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_date_devolucion.setText("")
        self.entrada_date_devolucion.setObjectName("entrada_date_devolucion")
        self.entrada_date_entrega = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_date_entrega.setGeometry(QtCore.QRect(210, 280, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_date_entrega.setFont(font)
        self.entrada_date_entrega.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_date_entrega.setText("")
        self.entrada_date_entrega.setObjectName("entrada_date_entrega")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 320, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.entrada_numero_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_numero_revista.setGeometry(QtCore.QRect(210, 230, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_numero_revista.setFont(font)
        self.entrada_numero_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_numero_revista.setText("")
        self.entrada_numero_revista.setObjectName("entrada_numero_revista")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 370, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checbox_descatalogado = QtWidgets.QCheckBox(self.centralwidget)
        self.checbox_descatalogado.setGeometry(QtCore.QRect(250, 370, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checbox_descatalogado.setFont(font)
        self.checbox_descatalogado.setObjectName("checbox_descatalogado")
        self.combo_extra = QtWidgets.QComboBox(self.centralwidget)
        self.combo_extra.setGeometry(QtCore.QRect(208, 430, 101, 22))
        self.combo_extra.setObjectName("combo_extra")
        self.combo_extra.addItem("")
        self.combo_extra.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 470, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.radio_semanal = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_semanal.setGeometry(QtCore.QRect(210, 480, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_semanal.setFont(font)
        self.radio_semanal.setChecked(True)
        self.radio_semanal.setObjectName("radio_semanal")
        self.radio_mensual = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_mensual.setGeometry(QtCore.QRect(370, 480, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_mensual.setFont(font)
        self.radio_mensual.setObjectName("radio_mensual")
        self.radio_anual = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_anual.setGeometry(QtCore.QRect(540, 480, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radio_anual.setFont(font)
        self.radio_anual.setObjectName("radio_anual")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.entrada_titulo_revista, self.entrada_precio_revista)
        MainWindow.setTabOrder(self.entrada_precio_revista, self.entrada_ditribuidor_revista)
        MainWindow.setTabOrder(self.entrada_ditribuidor_revista, self.entrada_numero_revista)
        MainWindow.setTabOrder(self.entrada_numero_revista, self.entrada_date_entrega)
        MainWindow.setTabOrder(self.entrada_date_entrega, self.entrada_date_devolucion)
        MainWindow.setTabOrder(self.entrada_date_devolucion, self.entrada_registrar_revista)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Introduce los Datos de la Revista"))
        self.label_2.setText(_translate("MainWindow", "Titulo"))
        self.label_3.setText(_translate("MainWindow", "Precio"))
        self.label_4.setText(_translate("MainWindow", "Distribuidor"))
        self.entrada_registrar_revista.setText(_translate("MainWindow", "REGISTRAR REVISTA"))
        self.label_5.setText(_translate("MainWindow", "Fecha de entrega"))
        self.label_7.setText(_translate("MainWindow", "Numero de Revista"))
        self.label_8.setText(_translate("MainWindow", "Fecha de devolucion"))
        self.label_9.setText(_translate("MainWindow", "Descatalogada"))
        self.checbox_descatalogado.setText(_translate("MainWindow", "Si"))
        self.combo_extra.setItemText(0, _translate("MainWindow", "sin cupon"))
        self.combo_extra.setItemText(1, _translate("MainWindow", "con cupon"))
        self.label_10.setText(_translate("MainWindow", "Extra"))
        self.label_11.setText(_translate("MainWindow", "Periodicidad"))
        self.radio_semanal.setText(_translate("MainWindow", "semanal"))
        self.radio_mensual.setText(_translate("MainWindow", "mensual"))
        self.radio_anual.setText(_translate("MainWindow", "anual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
