# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_editar_revistas.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 691, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_titulo_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_titulo_revista.setGeometry(QtCore.QRect(210, 110, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_titulo_revista.setFont(font)
        self.entrada_titulo_revista.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(170, 255, 0);")
        self.entrada_titulo_revista.setText("")
        self.entrada_titulo_revista.setObjectName("entrada_titulo_revista")
        self.entrada_precio_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio_revista.setGeometry(QtCore.QRect(210, 160, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_precio_revista.setFont(font)
        self.entrada_precio_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_precio_revista.setText("")
        self.entrada_precio_revista.setObjectName("entrada_precio_revista")
        self.entrada_ditribuidor_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_ditribuidor_revista.setGeometry(QtCore.QRect(210, 210, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_ditribuidor_revista.setFont(font)
        self.entrada_ditribuidor_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_ditribuidor_revista.setText("")
        self.entrada_ditribuidor_revista.setObjectName("entrada_ditribuidor_revista")
        self.boton_guardar_cambios_revista = QtWidgets.QPushButton(self.centralwidget)
        self.boton_guardar_cambios_revista.setGeometry(QtCore.QRect(240, 482, 321, 81))
        self.boton_guardar_cambios_revista.setStyleSheet("alternate-background-color: rgb(61, 165, 255);\n"
"background-color: rgb(56, 142, 255);\n"
"border-color: rgb(32, 47, 255);")
        self.boton_guardar_cambios_revista.setObjectName("boton_guardar_cambios_revista")
        self.entrada_date_devolucion = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_date_devolucion.setGeometry(QtCore.QRect(210, 360, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_date_devolucion.setFont(font)
        self.entrada_date_devolucion.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_date_devolucion.setText("")
        self.entrada_date_devolucion.setObjectName("entrada_date_devolucion")
        self.entrada_date_entrega = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_date_entrega.setGeometry(QtCore.QRect(210, 310, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_date_entrega.setFont(font)
        self.entrada_date_entrega.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_date_entrega.setText("")
        self.entrada_date_entrega.setObjectName("entrada_date_entrega")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 250, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 350, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.entrada_numero_revista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_numero_revista.setGeometry(QtCore.QRect(210, 260, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrada_numero_revista.setFont(font)
        self.entrada_numero_revista.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.entrada_numero_revista.setText("")
        self.entrada_numero_revista.setObjectName("entrada_numero_revista")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.entrada_titulo_revista, self.entrada_precio_revista)
        MainWindow.setTabOrder(self.entrada_precio_revista, self.entrada_ditribuidor_revista)
        MainWindow.setTabOrder(self.entrada_ditribuidor_revista, self.entrada_numero_revista)
        MainWindow.setTabOrder(self.entrada_numero_revista, self.entrada_date_entrega)
        MainWindow.setTabOrder(self.entrada_date_entrega, self.entrada_date_devolucion)
        MainWindow.setTabOrder(self.entrada_date_devolucion, self.boton_guardar_cambios_revista)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "INTRODUCE LOS NUEVOS DATOS DE LA REVISTA"))
        self.label_2.setText(_translate("MainWindow", "Titulo"))
        self.label_3.setText(_translate("MainWindow", "Precio"))
        self.label_4.setText(_translate("MainWindow", "Distribuidor"))
        self.boton_guardar_cambios_revista.setText(_translate("MainWindow", "GUARDAR CAMBIOS"))
        self.label_5.setText(_translate("MainWindow", "Fecha de entrega"))
        self.label_7.setText(_translate("MainWindow", "Numero de Revista"))
        self.label_8.setText(_translate("MainWindow", "Fecha de devolucion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
